version: '2.1'

services:
#  searchingapp:
#    container_name: searchingapp
#    build: .
#    working_dir: /webfluxelastic
#    ports:
#      - 8080:8080
#    volumes:
#      - .:/webfluxelastic/searchingapp
#    tty: true
#    command: mvn clean spring-boot:run
#    restart: unless-stopped
#    depends_on:
#      - elasticsearch
#      - kibana

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: elastic-search
    ports:
      - 9300:9300
      - 9200:9200
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    networks:
      backend:
        aliases:
          - "elasticsearch"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9300
    ports:
        - 5601:5601
    depends_on:
        - elasticsearch
    networks:
      backend:
          aliases:
            - "kibana"

networks:
  backend:
    driver: bridge